### ISSUE TITLE
Bump puppeteer

### ISSUE THREAD

**Issue by brendonbarreto** [mercos/robot-eyes#114]
@dependabot created an PR (https://github.com/mercos/robot-eyes/pull/105) for that, but is not as easy as one button click. This is because the project's node version is 10.15.0, and the latest version of puppeteer uses node 10.18.1.

So here we will need to update the node version to 10.18.1, then bump puppeteer.

**Comment by inacior** [comment]
Hi!

Can I work on it?

**Comment by brendonbarreto** [comment]
Yes! Let me know if you need some help!

**Comment by inacior** [comment]
I opened the #116 for this

**Comment by brendonbarreto** [comment]
Thanks @inacior!
