### ISSUE TITLE
Replace puppeteer.waitFor for his equivalent functions

### ISSUE THREAD

**Issue by brendonbarreto** [mercos/robot-eyes#119]
Puppeteer decided to deprecate `waitFor` function (https://github.com/puppeteer/puppeteer/issues/6214). There are few places that we use this function, but we need to use the equivalents, as they mention in the issue.

In our case, we only use the function they just implemented called `waitForTimeout`. My implementation suggestion would be to delete the file https://github.com/mercos/robot-eyes/blob/master/capture/waitFor.js, and replace with `page.waitForTimeout`.

And in places where the `page.waitFor` function is called, see if what it is receiving is an integer or a string:
- String: replace `page.waitFor` -> `page.waitForSelector`
- Integer: replace `page.waitFor` -> `page.waitForTimeout`

**Comment by greyGroot** [comment]
can i work on this one?

**Comment by brendonbarreto** [comment]
@greyGroot Yes, go for it! Let me know if you need some help.

**Comment by rohan2734** [comment]
@greyGroot is anyone assigned on it ?or can i work on this issue?

**Comment by greyGroot** [comment]
sorry, @rohan2734 i'm working on it

**Comment by rohan2734** [comment]
> sorry, @rohan2734 i'm working on it

ok no problem

**Comment by greyGroot** [comment]
@brendonbarreto unfortunately i don't understand how to do it. Could you please assign this task to @rohan2734 ? If he still want to work on it.

**Comment by rohan2734** [comment]
@brendonbarreto no i don't want to work now.
